Pose module unit tests
RobotecAI/scenario_simulator_v2 pull request #37
Opened 2024-09-09 07:39 UTC by gmajrobotec

# Description

## Abstract

This PR contains unit tests for the pose namespace, which is a part of traffic_simulator package

## Details
List of tests included in this PR:
1. pose.quietNaNPose
2. pose.quietNaNLaneletPose
3. pose.canonicalize_default
4. pose.canonicalize_invalid
5. pose.canonicalize_valid
6. pose.toMapPose_CanonicalizedLaneletPosepose.toMapPose_LaneletPose
7. pose.toCanonicalizedLaneletPose_noBoundingBox_noRoute_valid
8. pose.toCanonicalizedLaneletPose_noBoundingBox_noRoute_invalid
9. pose.toCanonicalizedLaneletPose_BoundingBox_noRoute_valid
10. pose.toCanonicalizedLaneletPose_BoundingBox_noRoute_invalid
11. pose.toCanonicalizedLaneletPose_BoundingBox_route_emptyInvalid
12. pose.toCanonicalizedLaneletPose_BoundingBox_route_emptyValid
13. pose.toCanonicalizedLaneletPose_BoundingBox_route_nonEmptyInvalid
14. pose.toCanonicalizedLaneletPose_BoundingBox_route_nonEmptyValid
15. pose.transformRelativePoseToGlobal
16. pose.relativePose_poses_zeros
17. pose.relativePose_poses_zero
18. pose.relativePose_poses_complex
19. pose.relativePose_first
20. pose.relativePose_second
21. pose.boundingBoxRelativePose_disjoint
22. pose.boundingBoxRelativePose_commonEdge
23. pose.boundingBoxRelativePose_intersect
24. pose.relativeLaneletPose_s_invalid
25. pose.relativeLaneletPose_s_valid
26. pose.relativeLaneletPose_offset_invalid
27. pose.relativeLaneletPose_offset_valid
28. pose.boundingBoxRelativeLaneletPose_s_invalid
29. pose.boundingBoxRelativeLaneletPose_s_valid
30. pose.boundingBoxRelativeLaneletPose_offset_invalid
31. pose.boundingBoxRelativeLaneletPose_offset_valid
32. pose.isInLanelet_inside
33. pose.isInLanelet_outsideFrontFar
34. pose.isInLanelet_outsideFrontClose
35. pose.isInLanelet_outsideBackFar
36. pose.isInLanelet_outsideBackClose
37. pose.isAtEndOfLanelets_noFollowing_within
38. pose.isAtEndOfLanelets_singleFollowing_within
39. pose.isAtEndOfLanelets_singleFollowing_outside
40. pose.isAtEndOfLanelets_multipleFollowing_within
41. pose.isAtEndOfLanelets_multipleFollowing_outside
42. pose.laneletLength_invalid
43. pose.laneletLength_valid

## References
Jira ticket: [internal link](https://tier4.atlassian.net/browse/RJD-1197)

# Destructive Changes

There are no destructive changes.

2024-09-09 11:20 UTC, robomic requested changes
Only style changes, apply them throughout the entire file

2024-09-09 11:20 UTC, robomic commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_NEAR(relative.s, 107.74, 0.001);
EXPECT_DOUBLE_NEAR

2024-09-09 11:20 UTC, robomic commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  const auto boundingBox = makeBoundingBox();
rename const auto bounding_box

2024-09-09 12:37 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> + * @note test created object values
done

2024-09-09 12:37 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_TRUE(isnan(pose.position.z));
done

2024-09-09 12:38 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_EQ(pose.orientation.w, 1);
done

2024-09-09 12:38 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_TRUE(isnan(pose.rpy.z));
done

2024-09-09 12:40 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +    geometry_msgs::build<geometry_msgs::msg::Quaternion>().x(0).y(0).z(-0.6397).w(0.7686));
done

2024-09-09 12:40 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +      pose, makeBoundingBox(), {}, true, 1.0, hdmap_utils),
done

2024-09-09 12:41 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_NEAR(relative.s, 107.74, 0.001);
done

2024-09-09 13:08 UTC, robomic approved these changes
fix those style issues and it's good ;)

2024-09-09 13:38 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  const geometry_msgs::msg::Pose pose = makePose(makePoint(0, 0, 0));
done

2024-09-09 13:39 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +    pose, makeBoundingBox(), {}, true, 1.0, hdmap_utils);
done

2024-09-09 13:39 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  const geometry_msgs::msg::Pose pose = makePose(makePoint(0, 0, 0));
done

2024-09-09 13:39 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +    pose, makeBoundingBox(), {195}, true, 1.0, hdmap_utils);
done

2024-09-09 13:41 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_FALSE(traffic_simulator::pose::isInLanelet(pose, 3002163, 1, hdmap_utils));
done

2024-09-09 13:41 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_FALSE(traffic_simulator::pose::isInLanelet(pose, 195, 2, hdmap_utils));
done

2024-09-09 13:42 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_TRUE(traffic_simulator::pose::isInLanelet(pose, 195, 10, hdmap_utils));
done

2024-09-10 08:51 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/utils/test_pose.cpp
> +  EXPECT_TRUE(traffic_simulator::pose::isInLanelet(pose, 195, 0, hdmap_utils));
changed to std::numeric_limits<double>::epsilon()

2024-10-01 10:06 UTC, merged