Fix getQuadraticAccelerationDuration returning negative duration
RobotecAI/scenario_simulator_v2 pull request #39
Opened 2024-10-01 09:35 UTC by gmajrobotec

# Description

## Abstract
Function getQuadraticAccelerationDuration can return a negative duration. It is possible because getQuadraticAccelerationDurationWithConstantJerk is being invoked if-and-only-if v and target_speed are almost equal, which does not seem correct. This part of the code also seems incongruent with the comments in 185, 189, 199 and 203.

## Details
Comparison `if (std::abs(v - target_speed) >= 0.01)` in getQuadraticAccelerationDuration is changed to `if (v < target_speed) ` ensuring return duration is not negative.

## References
Jira ticket: [internal link](https://tier4.atlassian.net/browse/RJD-1337)

# Destructive Changes

There are no destructive changes.

2024-10-01 10:20 UTC, robomic requested changes
Please explain the change and why should it work in the PR description.
Use `code` for variable/function names in the description.
Use permalinks instead of line numbers like so:
https://github.com/tier4/scenario_simulator_v2/blob/a3e59a7051400776473288eceb2e4198082b4215/simulation/traffic_simulator/src/behavior/longitudinal_speed_planning.cpp#L185-L187

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> + * and target_speed is more than 0.01
done

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> +TEST_F(LongitudinalSpeedPlannerTest, example)
done

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> +  const double epsilon = 1e-5;
done

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> +  double target_speed, result_duration;
done

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> +    result_duration =
done

2024-10-02 10:53 UTC, gmajrobotec commented on simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
> +    target_speed = current_twist.linear.x + epsilon;
done

2024-10-02 17:50 UTC, robomic approved these changes
LGTM

2024-11-07 15:29 UTC, merged