Change detection of front entity on path of NPC
RobotecAI/scenario_simulator_v2 pull request #45
Opened 2024-12-09 01:27 UTC by gmajrobotec

# Description

NPC should  detect another Entity with see_around even when the Entity does not overlap the center line of the lane which the NPC is on. This change allows to detect another NPC which overlap path of this NPC. 

## Abstract

This PR changes detection function of front entity in `ActionNode`.

## Details

I've changed `getDistanceToTargetEntityPolygon` to use spline polygon with width of NPC bounding box to check if another NPC overlaps current NPC path. If so distance is calculated using `boundingBoxRelativePose` method.

# Destructive Changes

--

# Known Limitations

--

2024-12-11 12:32 UTC, piotr-zyskowski-rai requested changes

2024-12-11 13:38 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +// #include <traffic_simulator/data_type/lanelet_pose.hpp>
done

2024-12-11 18:03 UTC, dmoszynski requested changes
a few stylistic changes, let me know what do you think, note: compilable, untested

2024-12-11 18:03 UTC, dmoszynski commented on simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
> +  distance_to_front_entity_ = getDistanceToTargetEntityPolygon(front_entity_name.value());
```
  const auto & front_entity_status = getEntityStatus(front_entity_name.value());
  distance_to_front_entity_ = getDistanceToTargetEntityPolygon(front_entity_status);
  ```
  `front_entity_status` is used further

2024-12-11 18:03 UTC, dmoszynski commented on simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
> +    auto distance_to_front_entity = getDistanceToFrontEntity();
```suggestion
    const auto distance_to_front_entity = getDistanceToFrontEntity();
```

2024-12-12 08:22 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +  auto name = getFrontEntityName();
done

2024-12-12 08:23 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
> +    auto distance_to_front_entity = getDistanceToFrontEntity();
done

2024-12-12 08:53 UTC, dmoszynski approved these changes
:+1:

2025-01-24 11:14 UTC, dmoszynski commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +    }
```
auto ActionNode::getDistanceToTargetEntityPolygon(
  const math::geometry::CatmullRomSplineInterface & spline,
  const traffic_simulator::CanonicalizedEntityStatus & status) const -> std::optional<double>
{
  if (
    status.laneMatchingSucceed() && canonicalized_entity_status->laneMatchingSucceed() &&
    isOtherEntityAtConsideredAltitude(status)) {
    /* 
     * boundingBoxRelativeLaneletPose requires routing_configuration, 
     * 'allow_lane_change = true' is needed to check distances to entities on neighbour lanelets
     */
    traffic_simulator::RoutingConfiguration routing_configuration;
    routing_configuration.allow_lane_change = true;
    constexpr bool include_adjacent_lanelet{false};
    constexpr bool include_opposite_direction{true};
    constexpr bool search_backward{false};

    const auto & target_bounding_box = status.getBoundingBox();
    const auto & target_lanelet_pose =
      traffic_simulator::pose::tranformToRoutableCanonicalizedLaneletPose(
        canonicalized_entity_status->getLaneletId(), status.getCanonicalizedLaneletPose().value(),
        target_bounding_box, hdmap_utils);

    if (target_lanelet_pose) {
      const auto & from_lanelet_pose = canonicalized_entity_status->getCanonicalizedLaneletPose();
      const auto & from_bounding_box = canonicalized_entity_status->getBoundingBox();
      if (const auto bounding_box_distance =
            traffic_simulator::distance::boundingBoxLaneLongitudinalDistance(
              *from_lanelet_pose, from_bounding_box, *target_lanelet_pose, target_bounding_box,
              include_adjacent_lanelet, include_opposite_direction, routing_configuration,
              hdmap_utils);
          not bounding_box_distance || bounding_box_distance.value() < 0.0) {
        return std::nullopt;
      } else if (const auto position_distance = traffic_simulator::distance::longitudinalDistance(
                   *from_lanelet_pose, *target_lanelet_pose, include_adjacent_lanelet,
                   include_opposite_direction, routing_configuration, hdmap_utils);
                 not position_distance) {
        return std::nullopt;
      } else {
        const auto target_bounding_box_distance =
          bounding_box_distance.value() + from_bounding_box.dimensions.x / 2.0;

        /// @note if the distance of the target entity to the spline is smaller than the width of the reference entity
        if (const auto target_to_spline_distance = traffic_simulator::distance::distanceToSpline(
              static_cast<geometry_msgs::msg::Pose>(*target_lanelet_pose), target_bounding_box,
              spline, position_distance.value());
            target_to_spline_distance <= from_bounding_box.dimensions.y / 2.0) {
          return target_bounding_box_distance;
        }
        /// @note if the distance of the target entity to the spline cannot be calculated because a collision occurs
        else if (const auto target_polygon = math::geometry::transformPoints(
                   status.getMapPose(), math::geometry::getPointsFromBbox(target_bounding_box));
                 spline.getCollisionPointIn2D(target_polygon, search_backward)) {
          return target_bounding_box_distance;
        }
      }
    }
  }
  return std::nullopt;
}

```

2025-01-24 11:17 UTC, dmoszynski commented on simulation/traffic_simulator/include/traffic_simulator/utils/pose.hpp
> +auto tranformToRoutableCanonicalizedLaneletPose(
tran**s**formToRoutableCanonicalizedLaneletPose

2025-01-24 11:20 UTC, dmoszynski commented on simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
> +  std::set<std::pair<double, lanelet::Id>> id_and_distance;
`id_and_distance` -> `distances_with_ids`

2025-01-24 11:22 UTC, dmoszynski commented on simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
> +  return id_and_distance;
```
  if (not matches.empty()) {
    std::set<std::pair<double, lanelet::Id>> distances_with_ids;
    for (const auto & match : matches) {
      if (
        const auto lanelet_pose = toLaneletPose(map_pose, match.lanelet.id(), matching_distance)) {
        distances_with_ids.emplace(lanelet_pose->offset, lanelet_pose->lanelet_id);
      }
    }
    if (not distances_with_ids.empty()) {
      return distances_with_ids;
    }
  }
  return std::nullopt;
```

2025-01-24 11:27 UTC, dmoszynski commented on simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
> +  return std::nullopt;
```suggestion
{
  /// @note findMatchingLanes returns a container sorted by distance - increasing, return the nearest id
  if (
    const auto matching_lanes =
      findMatchingLanes(pose, bbox, include_crosswalk, matching_distance, reduction_ratio, type)) {
    return matching_lanes->begin()->second;
  } else {
    return std::nullopt;
  }
```

2025-01-24 11:32 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/distance.cpp
> +    while (std::abs(s_start_distance - s_end_distance) > distance_accuracy) {
`while (std::abs(s_start_distance - s_end_distance) > distance_accuracy && std::abs(s_start - s_end) > distance_accuracy) {`
because without this, if there are two equal distances `s_start_distance` and `s_end_distance` the loop will end but they may be very far away from each other along the spline 
(s_start = 10, s_end = 20, s_start_distance=9.96, s_end_distance=10.00)

2025-01-24 11:35 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +  if (!hdmap_utils_ptr->getRoute(from_lanelet_id, to_lanelet_id, routing_configuration).empty()) {
`if(not ..)` - please apply this to all changes (I have recently noticed that this is expected)

2025-01-24 11:37 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +               include_crosswalk, search_distance, 0.8, routing_configuration.routing_graph_type);
0.8 as constexpr and explanation - add an explanation to each constexpr in this PR (also RoutingConfiguration)

2025-01-24 11:40 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +        routes.emplace_back(std::make_pair(canonicalized.value(), route));
try `routes.emplace_back(std::move(canonicalized.value()), std::move(route));`

2025-01-24 11:41 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +      return std::min_element(
add explanation about this approach

2025-01-24 11:41 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +  return std::nullopt;
always if u can use if(){}else{} apply this

2025-01-24 11:42 UTC, dmoszynski commented on simulation/traffic_simulator/src/utils/pose.cpp
> +  const lanelet::Id from_lanelet_id, const CanonicalizedLaneletPose & canonicalized_lanelet_pose,
`to_canonicalized_lanelet_pose`

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +  const traffic_simulator::CanonicalizedEntityStatus & status) const -> std::optional<double>
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +      const auto longitudinal_target_distance = traffic_simulator::distance::longitudinalDistance(
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/behavior_tree_plugin/src/action_node.cpp
> +      if (longitudinal_target_distance) {
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/pose.cpp
> +               include_crosswalk, search_distance, 0.8, routing_configuration.routing_graph_type);
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/pose.cpp
> +        routes.emplace_back(std::make_pair(canonicalized.value(), route));
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/pose.cpp
> +  return std::nullopt;
done

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/pose.cpp
> +  if (!hdmap_utils_ptr->getRoute(from_lanelet_id, to_lanelet_id, routing_configuration).empty()) {
This could be not true, we will check with sonarcloud.

2025-01-24 13:35 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/distance.cpp
> +    while (std::abs(s_start_distance - s_end_distance) > distance_accuracy) {
Finally there should be just std::abs(s_start - s_end) > distance_accuracy

2025-01-24 13:36 UTC, gmajrobotec commented on simulation/traffic_simulator/src/utils/pose.cpp
> +      return std::min_element(
done

2025-02-12 14:21 UTC, merged